# Generated by Django 3.2.5 on 2021-09-12 11:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Books', '0007_alter_book_issuedto'),
        ('Users', '0002_user_fine'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='favorites',
            field=models.ManyToManyField(blank=True, null=True, to='Books.Book'),
        ),
    ]
