# Generated by Django 3.2.5 on 2021-09-19 08:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Books', '0007_alter_book_issuedto'),
        ('Users', '0003_alter_user_favorites'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='favorites',
            field=models.ManyToManyField(blank=True, to='Books.Book'),
        ),
    ]
